### PR TITLE
Switch to PyPy

### PR DESCRIPTION
**Pull request by simonw**

### CODE REVIEW

**Comment by simonw** [comment]
Since the tests are all passing, I deployed this branch for a few minutes to see how it would behave. No Sentry errors, but memory usage on Heroku wasn't great compared to regular CPython so I rolled back again:

simonwillisonblog_ _metrics___heroku

**Comment by simonw** [comment]
Posted about this here: https://simonwillison.net/2017/Nov/5/try-hosting-on-pypy/

**Comment by simonw** [comment]
Affect on response time wasn't great either:

banners_and_alerts_and_simonwillisonblog_ _metrics___heroku

**Comment by fijal** [comment]
The response time would *eventually* stabilize to be ~50% of CPython, but the memory will likely stay higher. Django ORM is insane, I don't know how you can sanely JIT compile it.

**Pull request closed without merging**
